name: Create draft release on tag
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'Src'
            exclude: ''
          - check: 'Inc'
            exclude: ''
          - check: 'Mcu'
            exclude: '(Drivers)'

    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: ${{ matrix.path }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'WebKit' # optional
